//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleSqlite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleSqlite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add column &quot;{0}&quot; to the primary key of table &quot;{1}&quot;. The column does not belong to the table..
        /// </summary>
        internal static string CannotAddColumnFromOtherTableToPK {
            get {
                return ResourceManager.GetString("CannotAddColumnFromOtherTableToPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add the row to the table &quot;{0}&quot;. The table already contains a row with the same primary key value..
        /// </summary>
        internal static string CannotAddDuplicatedPrimaryKey {
            get {
                return ResourceManager.GetString("CannotAddDuplicatedPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add the foreign key column &quot;{0}&quot; to the table &quot;{1}&quot;. Adding foreign keys to existing tables is not supported by SQLite..
        /// </summary>
        internal static string CannotAddForeignKeyToAttachedTable {
            get {
                return ResourceManager.GetString("CannotAddForeignKeyToAttachedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add the foreign key column &quot;{0}&quot; to the table &quot;{1}&quot;. Specified primary key column &quot;{2}&quot; should be linked with a table..
        /// </summary>
        internal static string CannotAddForeignKeyToColumnWithoutTable {
            get {
                return ResourceManager.GetString("CannotAddForeignKeyToColumnWithoutTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add the foreign key column &quot;{0}&quot; to the table &quot;{1}&quot;. Specified primary key column &quot;{2}&quot; from table &quot;{3}&quot; is not a primary key column..
        /// </summary>
        internal static string CannotAddForeignKeyToNotPrimary {
            get {
                return ResourceManager.GetString("CannotAddForeignKeyToNotPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add NotNull column &quot;{0}&quot; to an existing table. Default value must be set..
        /// </summary>
        internal static string CannotAddNotNullWithoutValue {
            get {
                return ResourceManager.GetString("CannotAddNotNullWithoutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add column &quot;{0}&quot;. Primary key columns can not be added to existing tables..
        /// </summary>
        internal static string CannotAddPrimaryKey {
            get {
                return ResourceManager.GetString("CannotAddPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add the cell to column &quot;{0}&quot;. The cell for this column already exists..
        /// </summary>
        internal static string CannotAddToAttachedRow {
            get {
                return ResourceManager.GetString("CannotAddToAttachedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not caculate average of the provided type &quot;{0}&quot;..
        /// </summary>
        internal static string CannotAverageType {
            get {
                return ResourceManager.GetString("CannotAverageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value provided for column &quot;{0}&quot; is null, but the column is not nullable..
        /// </summary>
        internal static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change column &quot;{0}&quot;. Columns added to an existing table can not be changed..
        /// </summary>
        internal static string CannotChangeAttachedColumn {
            get {
                return ResourceManager.GetString("CannotChangeAttachedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add or remove column &quot;{0}&quot; to/from primary key. Primary key columns can not be changed in existing tables..
        /// </summary>
        internal static string CannotChangePrimaryKey {
            get {
                return ResourceManager.GetString("CannotChangePrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove the cell, as it is linked to existing column &quot;{0}&quot;..
        /// </summary>
        internal static string CannotRemoveAttachedCell {
            get {
                return ResourceManager.GetString("CannotRemoveAttachedCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove column &quot;{0}&quot; from table &quot;{1}&quot;. Column deletion is not supported by SQLite..
        /// </summary>
        internal static string CannotRemoveAttachedColumn {
            get {
                return ResourceManager.GetString("CannotRemoveAttachedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not sum arguments of types &quot;{0}&quot; and &quot;{1}&quot;..
        /// </summary>
        internal static string CannotSumTypes {
            get {
                return ResourceManager.GetString("CannotSumTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add cell &quot;{0}&quot; to the row. The cell is already added to another row..
        /// </summary>
        internal static string CellAlreadyAttached {
            get {
                return ResourceManager.GetString("CellAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not link cell &quot;{0}&quot; to the current table. The cell already belongs to a column from another table..
        /// </summary>
        internal static string CellAlreadyAttachedToInvalidColumn {
            get {
                return ResourceManager.GetString("CellAlreadyAttachedToInvalidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add column &quot;{0}&quot; to table &quot;{1}&quot;. The column is already added to another table..
        /// </summary>
        internal static string ColumnAlreadyAttached {
            get {
                return ResourceManager.GetString("ColumnAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add foreign key cell into column &quot;{0}&quot;. The column is not a foreign key column..
        /// </summary>
        internal static string ColumnIsNotForeignKey {
            get {
                return ResourceManager.GetString("ColumnIsNotForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add foreign key cell into column &quot;{0}&quot;. The column&apos;s foreign key is related to table &quot;{1}&quot;, but the primary row table is &quot;{2}&quot;..
        /// </summary>
        internal static string ColumnIsNotForeignKeyToPrimaryRow {
            get {
                return ResourceManager.GetString("ColumnIsNotForeignKeyToPrimaryRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column with a name &quot;{0}&quot; is not found..
        /// </summary>
        internal static string ColumnNotFound {
            get {
                return ResourceManager.GetString("ColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cell already exists in the same row and column &quot;{0}&quot;..
        /// </summary>
        internal static string DuplicatedCell {
            get {
                return ResourceManager.GetString("DuplicatedCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A column with the same name &quot;{0}&quot; already exists in the table &quot;{1}&quot;..
        /// </summary>
        internal static string DuplicatedColumn {
            get {
                return ResourceManager.GetString("DuplicatedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table with the same name &quot;{0}&quot; already exists in the database..
        /// </summary>
        internal static string DuplicatedTable {
            get {
                return ResourceManager.GetString("DuplicatedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BLOB string &quot;{0}&quot;. BLOB string must contain hexadecimal data in quotes preceded by a single &quot;x&quot; or &quot;X&quot; character..
        /// </summary>
        internal static string InvalidBLOBString {
            get {
                return ResourceManager.GetString("InvalidBLOBString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;{0}&quot; default value &quot;{1}&quot; is either invalid or does not match column type &quot;{2}&quot;..
        /// </summary>
        internal static string InvalidColumnDefaultValue {
            get {
                return ResourceManager.GetString("InvalidColumnDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid column name &quot;{0}&quot;. A column name should not be null, empty, whitespace or contain double quote character..
        /// </summary>
        internal static string InvalidColumnName {
            get {
                return ResourceManager.GetString("InvalidColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid table name &quot;{0}&quot;. A table name should not be null, empty, whitespace or contain double quote character..
        /// </summary>
        internal static string InvalidTableName {
            get {
                return ResourceManager.GetString("InvalidTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type &quot;{0}&quot; have been provided for a list column cell, but it is not one of the supported list types..
        /// </summary>
        internal static string IsNotSupportedArrayType {
            get {
                return ResourceManager.GetString("IsNotSupportedArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &quot;{0}&quot; does not have any columns. Zero-column tables are not supported by SQLite..
        /// </summary>
        internal static string MustHaveColumns {
            get {
                return ResourceManager.GetString("MustHaveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary column for foreign key column &quot;{0}&quot; can not be null..
        /// </summary>
        internal static string NullPrimaryColumn {
            get {
                return ResourceManager.GetString("NullPrimaryColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add foreign key cell to column &quot;{0}&quot;. Specified primary key row is not linked with a table..
        /// </summary>
        internal static string PrimaryRowMustBeAttached {
            get {
                return ResourceManager.GetString("PrimaryRowMustBeAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add the row to table &quot;{0}&quot;. Cells should be added for all non-nullable columns without default value..
        /// </summary>
        internal static string RequiredCellsMissed {
            get {
                return ResourceManager.GetString("RequiredCellsMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add the row to table &quot;{0}&quot;. The row is already added to another table..
        /// </summary>
        internal static string RowAlreadyAttached {
            get {
                return ResourceManager.GetString("RowAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong type provided for a cell in column &quot;{0}&quot;. Type should be one of the list types, but actual type is &quot;{1}&quot;..
        /// </summary>
        internal static string ShouldBeListType {
            get {
                return ResourceManager.GetString("ShouldBeListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong type provided for a cell in column &quot;{0}&quot;. Type should be one of the singular types, but actual type is &quot;{1}&quot;..
        /// </summary>
        internal static string ShouldBeSingleType {
            get {
                return ResourceManager.GetString("ShouldBeSingleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add table &quot;{0}&quot; to the database. The table is already added to another database..
        /// </summary>
        internal static string TableAlreadyAttached {
            get {
                return ResourceManager.GetString("TableAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table with a name &quot;{0}&quot; is not found..
        /// </summary>
        internal static string TableNotFound {
            get {
                return ResourceManager.GetString("TableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add the row to the table &quot;{0}&quot;. The row does not have cells. At least one cell should be specified..
        /// </summary>
        internal static string ZeroCellsInsert {
            get {
                return ResourceManager.GetString("ZeroCellsInsert", resourceCulture);
            }
        }
    }
}
